# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './dh_key.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 0, 511, 111))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 140, 81, 31))
        self.label_2.setObjectName("label_2")
        self.txt_param = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_param.setGeometry(QtCore.QRect(140, 130, 461, 87))
        self.txt_param.setObjectName("txt_param")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 280, 81, 31))
        self.label_3.setObjectName("label_3")
        self.txt_pubkey = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_pubkey.setGeometry(QtCore.QRect(140, 280, 461, 87))
        self.txt_pubkey.setObjectName("txt_pubkey")
        self.txt_shared = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_shared.setGeometry(QtCore.QRect(140, 410, 461, 87))
        self.txt_shared.setObjectName("txt_shared")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 410, 81, 31))
        self.label_4.setObjectName("label_4")
        self.btn_gen_param = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gen_param.setGeometry(QtCore.QRect(640, 130, 93, 41))
        self.btn_gen_param.setObjectName("btn_gen_param")
        self.btn_gen_key = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gen_key.setGeometry(QtCore.QRect(640, 280, 93, 41))
        self.btn_gen_key.setObjectName("btn_gen_key")
        self.btn_shared = QtWidgets.QPushButton(self.centralwidget)
        self.btn_shared.setGeometry(QtCore.QRect(640, 410, 93, 41))
        self.btn_shared.setObjectName("btn_shared")
        self.btn_load_pub = QtWidgets.QPushButton(self.centralwidget)
        self.btn_load_pub.setGeometry(QtCore.QRect(690, 10, 93, 41))
        self.btn_load_pub.setObjectName("btn_load_pub")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "DH_KEY_PAIR"))
        self.label_2.setText(_translate("MainWindow", "Parameter"))
        self.label_3.setText(_translate("MainWindow", "Public key"))
        self.label_4.setText(_translate("MainWindow", "Shared secret"))
        self.btn_gen_param.setText(_translate("MainWindow", "Gen para"))
        self.btn_gen_key.setText(_translate("MainWindow", "Gen key"))
        self.btn_shared.setText(_translate("MainWindow", "Gen shared"))
        self.btn_load_pub.setText(_translate("MainWindow", "Load PublicKey"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
