# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './hash.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(738, 600)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 0, 511, 111))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 80, 151, 81))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 380, 151, 81))
        self.label_3.setObjectName("label_3")
        self.txt_output = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_output.setGeometry(QtCore.QRect(90, 380, 571, 151))
        self.txt_output.setObjectName("txt_output")
        self.txt_input = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_input.setGeometry(QtCore.QRect(90, 110, 571, 151))
        self.txt_input.setObjectName("txt_input")
        self.bth_md5 = QtWidgets.QPushButton(self.centralwidget)
        self.bth_md5.setGeometry(QtCore.QRect(80, 290, 93, 28))
        self.bth_md5.setObjectName("bth_md5")
        self.bttn_sha3 = QtWidgets.QPushButton(self.centralwidget)
        self.bttn_sha3.setGeometry(QtCore.QRect(230, 290, 93, 28))
        self.bttn_sha3.setObjectName("bttn_sha3")
        self.bttn_sha256 = QtWidgets.QPushButton(self.centralwidget)
        self.bttn_sha256.setGeometry(QtCore.QRect(390, 290, 93, 28))
        self.bttn_sha256.setObjectName("bttn_sha256")
        self.btn_blake2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_blake2.setGeometry(QtCore.QRect(560, 290, 93, 28))
        self.btn_blake2.setObjectName("btn_blake2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 738, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Hash"))
        self.label_2.setText(_translate("MainWindow", "Text input"))
        self.label_3.setText(_translate("MainWindow", "Output"))
        self.bth_md5.setText(_translate("MainWindow", "MD5"))
        self.bttn_sha3.setText(_translate("MainWindow", "SHA-3"))
        self.bttn_sha256.setText(_translate("MainWindow", "SHA-256"))
        self.btn_blake2.setText(_translate("MainWindow", "Blake2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
